repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-json
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: pretty-format-json
        args:
          - --autofix
        exclude: ^tests/.+/profiles.d/.*
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: "master"
  #   hooks:
  #       - id: isort
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a1
    hooks:
      - id: pylint
        args:
          - --disable=C0103,C0302,C0330,E0401,R0205,R0801,R0902,R0903,R0904,R0912,R0913,R0914,R0915,R1702,W0212,W0511,W0703,W1202,R1725
        exclude: ^spamspy/.*
